In [ ]:
# 4.1 Exercise on Functions:

In [ ]:
# Task - 1:

In [ ]:
# Create a Python program that converts between different units of measurement.

In [15]:
def unit_converter():
    """
    A unit converter that allows the user to convert between different units of length, weight, and volume.
    Ask the user to input the value to be converted and display the result afterward.
    Handle error using try-except block.
    """
    
    def to_feet(meters):
        """Convert meters to feet."""
        return meters * 3.28084
    
    def to_meters(feet):
        """Convert feet to meters."""
        return feet / 3.28084
    
    def to_pounds(kg):
        """Convert kilograms to pounds."""
        return kg * 2.20462
    
    def to_kg(pounds):
        """Convert pounds to kilograms."""
        return pounds / 2.20462
    
    def to_gallons(liters):
        """Convert liters to gallons."""
        return liters * 0.264172
    
    def to_liters(gallons):
        """Convert gallons to liters."""
        return gallons / 0.264172

    print("Select a category to convert:") 
    print("1. Length\n2. Weight\n3. Volume")
    
    try:
        category = input("Enter your choice (1/2/3): ")
        
        if category == "1":
            print("1. Meters to Feet\n2. Feet to Meters")
            option = input("Choose conversion type (1/2): ")
            value = float(input("Enter the value: "))
            
            if option == "1":
                print(f"{value} meters is {to_feet(value):.2f} feet.")
            elif option == "2":
                print(f"{value} feet is {to_meters(value):.2f} meters.")
            else:
                print("Invalid selection.")
        
        elif category == "2":
            print("1. Kilograms to Pounds\n2. Pounds to Kilograms")
            option = input("Choose conversion type (1/2): ")
            value = float(input("Enter the value: "))
            
            if option == "1":
                print(f"{value} kg is {to_pounds(value):.2f} lbs.")
            elif option == "2":
                print(f"{value} lbs is {to_kg(value):.2f} kg.")
            else:
                print("Invalid selection.")
        
        elif category == "3":
            print("1. Liters to Gallons\n2. Gallons to Liters")
            option = input("Choose conversion type (1/2): ")
            value = float(input("Enter the value: "))
            
            if option == "1":
                print(f"{value} liters is {to_gallons(value):.2f} gallons.")
            elif option == "2":
                print(f"{value} gallons is {to_liters(value):.2f} liters.")
            else:
                print("Invalid selection.")
        else:
            print("Invalid category choice.")
    
    except ValueError:
        print("Invalid input. Please enter a numeric value.")

unit_converter()

Select a category to convert:
1. Length
2. Weight
3. Volume


Enter your choice (1/2/3):  1


1. Meters to Feet
2. Feet to Meters


Choose conversion type (1/2):  1
Enter the value:  25


25.0 meters is 82.02 feet.


In [ ]:
# Task - 2:

In [ ]:
# Create a Python program that performs various mathematical operations on a list of numbers.

In [21]:
def perform_math_operations():
    """
    Performs different mathematical calculations on a list of numbers.
    Ask the user to input a list of numbers and perform and display the result afterward.
    The function handles invalid inputs and ensures the program doesn't crash.
    """

    def get_sum(numbers):
        return sum(numbers)

    def get_average(numbers):
        return sum(numbers) / len(numbers) if numbers else 0

    def get_maximum(numbers):
        return max(numbers)

    def get_minimum(numbers):
        return min(numbers)

    print("Select an operation:")
    print("1. Sum of numbers")
    print("2. Average of numbers")
    print("3. Maximum value")
    print("4. Minimum value")

    operation = input("Enter your choice (1/2/3/4): ")

    try:
        """ Get user input and convert to a list of floats"""
        numbers = [float(num) for num in input("Provide numbers separated by spaces: ").split()]
        if not numbers:
            print("Error: The list of numbers cannot be empty.")
            return
    except ValueError:
        print("Error: Please input valid numeric values.")
        return

    if operation == "1":
        result = get_sum(numbers)
        print(f"Total sum: {result}")
    elif operation == "2":
        result = get_average(numbers)
        print(f"Average value: {result}")
    elif operation == "3":
        result = get_maximum(numbers)
        print(f"Largest number: {result}")
    elif operation == "4":
        result = get_minimum(numbers)
        print(f"Smallest number: {result}")
    else:
        print("Invalid operation selected. Please choose a valid option.")

perform_math_operations()

Select an operation:
1. Sum of numbers
2. Average of numbers
3. Maximum value
4. Minimum value


Enter your choice (1/2/3/4):  4
Provide numbers separated by spaces:  1 2 3 4 5 


Smallest number: 1.0


In [23]:
# 4.2 Exercise on List Manipulation:

In [ ]:
# 1. Extract Every Other Element:
# # Write a Python function that extracts every other element from a list, starting from the first element.

In [25]:
def extract_every_other(lst):
    return lst[::2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(input_list)
print(result)  # Output: [1, 3, 5]

[1, 3, 5]


In [27]:
# 2. Slice a Sublist:
# Write a Python function that returns a sublist from a given list, starting from a specified index and
# ending at another specified index.

In [29]:
def get_sublist(lst, start, end):
    return lst[start:end + 1]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
result = get_sublist(input_list, start_index, end_index)
print(result)  # Output: [3, 4, 5]

[3, 4, 5]


In [31]:
# 3. Reverse a List Using Slicing:
# Write a Python function that reverses a list using slicing.

In [33]:
def reverse_list(lst):
    return list(reversed(lst))

# Example usage:
input_list = [1, 2, 3, 4, 5]
result = reverse_list(input_list)
print(result)  # Output: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


In [35]:
# 4. Remove the First and Last Elements:
# Write a Python function that removes the first and last elements of a list and returns the resulting
# sublist.

In [39]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage:
input_list = [1, 2, 3, 4, 5]
result = remove_first_last(input_list)
print(result)  # Output: [2, 3, 4]

[2, 3, 4]


In [41]:
# 5. Get the First n Elements:
# Write a Python function that extracts the first n elements from a list.

In [43]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(input_list, n)
print(result)  # Output: [1, 2, 3]

[1, 2, 3]


In [ ]:
# 6. Extract Elements from the End:
# # Write a Python function that extracts the last n elements of a list using slicing.

In [45]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage:
input_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(input_list, n)
print(result)  # Output: [4, 5]

[4, 5]


In [47]:
# 7. Extract Elements in Reverse Order:
# Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
# element and skipping one element in between.

In [49]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(input_list)
print(result)  # Output: [5, 3, 1]

[5, 3, 1]


In [51]:
# 4.3 Exercise on Nested List:

In [53]:
# 1. Flatten a Nested List:
# Write a Python function that takes a nested list and flattens it into a single list, where all the elements
# # are in a single dimension.

In [61]:
def flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))
        else:
            flattened.append(item)
    return flattened

# Example usage:
input_list = [[1, 2], [3, 4], [5]]
result = flatten(input_list)
print(result)  # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [57]:
# 2. Accessing Nested List Elements:
# # Write a Python function that extracts a specific element from a nested list given its indices.

In [63]:
def access_nested_element(lst, indices):
    current = lst
    for index in indices:
        current = current[index]
    return current

# Example usage:
input_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(input_list, indices)
print(result)  # Output: 6

6


In [65]:
# 3. Sum of All Elements in a Nested List:
# Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [67]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else: 
            total += item
    return total

# Example usage:
input_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(input_list)
print(result)  # Output: 21

21


In [69]:
# 4. Remove Specific Element from a Nested List:
# Write a Python function that removes all occurrences of a specific element from a nested list.

In [71]:
def remove_element(lst, elem):
    return [[x for x in sublist if x != elem] for sublist in lst]

# Example usage:
input_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(input_list, element_to_remove)
print(result)  # Output: [[1], [3], [4, 5]]

[[1], [3], [4, 5]]


In [73]:
# 5. Find the Maximum Element in a Nested List:
# Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [75]:
def find_max(lst):
    max_elem = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)
    return max_elem

# Example usage:
input_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(input_list)
print(result)  # Output: 6

6


In [77]:
# 6. Count Occurrences of an Element in a Nested List:
# Write a Python function that counts how many times a specific element appears in a nested list.

In [79]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem: 
            count += 1
    return count

# Example usage:
input_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(input_list, element_to_count)
print(result)  # Output: 3

3


In [81]:
# 7. Flatten a List of Lists of Lists:
# Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [83]:
def deep_flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list): 
            flattened.extend(deep_flatten(item))
        else: 
            flattened.append(item)
    return flattened

# Example usage:
input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(input_list)
print(result)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [85]:
# 8. Nested List Average:
# Write a Python function that calculates the average of all elements in a nested list.

In [87]:
def average_nested(lst):
    total, count = 0, 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)  # Get total and count from sublist
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return (total, count) if count else (0, 0)  # Return total and count as a tuple

# Wrapper function to get only the average
def get_average(lst):
    total, count = average_nested(lst)
    return total / count if count else 0

# Example usage:
input_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(input_list)
print(result)  # Output: 3.5

(21, 6)


In [89]:
# Basic Vector and Matrix Operation with Numpy.

In [91]:
# Problem - 1: Array Creation:

In [93]:
# Complete the following Tasks:
# 1. Initialize an empty array with size 2X2.
# 2. Initialize an all one array with size 4X2.
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [105]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("2. All ones 4x2 array:\n")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 5)  # Shape: 3x3, Fill value: 5
print("3. Array filled with value 5:\n")
print(fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("4. Zeros array with same shape and type as given array:\n")
print(zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("5. Ones array with same shape and type as given array:\n")
print(ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. Converted NumPy array from list:\n")
print(numpy_array)

1. Empty 2x2 array:
[[2.12199579e-314 1.00370401e-311]
 [6.66000491e-321 1.00370401e-311]]
2. All ones 4x2 array:

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3. Array filled with value 5:

[[5 5 5]
 [5 5 5]
 [5 5 5]]
4. Zeros array with same shape and type as given array:

[[0 0]
 [0 0]]
5. Ones array with same shape and type as given array:

[[1 1]
 [1 1]]
6. Converted NumPy array from list:

[1 2 3 4]


In [97]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [101]:
# Complete the following tasks:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
# 4. Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
# 6. Create a zero array of size 10 and replace 5th element with 1.
# 7. Reverse an array arr = [1,2,0,0,4,0].
# 8. Create a 2d array with 1 on border and 0 inside.
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [117]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("1. Array with values ranging from 10 to 49\n")
print(range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 Matrix with values from 0 to 8:\n")
print(matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 Identity Matrix:\n")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("4. Random Array Mean:")
print(mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Min Value:", min_value)
print("Max Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Modified Zero Array:\n")
print(zero_array)

# 7. Reverse an array
array_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_array = array_to_reverse[::-1]
print("Reversed Array:\n")
print(reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("Border Array:\n")
print(border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:\n")
print(checkerboard)

1. Array with values ranging from 10 to 49

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3x3 Matrix with values from 0 to 8:

[[0 1 2]
 [3 4 5]
 [6 7 8]]
3. 3x3 Identity Matrix:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. Random Array Mean:
0.5047816500201
Min Value: 0.0070704688818381545
Max Value: 0.9700327340449103
Modified Zero Array:

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed Array:

[0 4 0 0 2 1]
Border Array:

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Checkerboard Pattern:

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [119]:
# Problem - 3: Array Operations:

In [121]:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
# 2. Subtract the two array.
# 3. Multiply the array with any integers of your choice.
# 4. Find the square of each element of the array.
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [123]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("1. Addition of x and y:")
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("2. Subtraction of x and y:\n")
print(subtract_result)

# 3. Multiply the array with any integer of your choice
multiply_result = x * 3  # Multiplying x by 3
print("3. Multiplication of x by 3:\n")
print(multiply_result)

# 4. Find the square of each element of the array
square_result = np.square(x)
print("4. Square of each element of x:\n")
print(square_result)

# 5. Find the dot product between v and w; x and v; x and y
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("5. Dot products:\n")
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)

# 6. Concatenate x and y along row and concatenate v and w along column
concatenate_row = np.concatenate((x, y), axis=0)  # Along rows
concatenate_column = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)  # Along columns
print("\n6. Concatenation:")
print("Concatenate x and y along row:")
print(concatenate_row)
print("Concatenate v and w along column:")
print(concatenate_column)

# 7. Concatenate x and v; if you get an error, observe and explain why
try:
    concatenate_x_v = np.concatenate((x, v))
    print("\n7. Concatenate x and v:")
    print(concatenate_x_v)
except ValueError as e:
    print("\n7. Error when concatenating x and v:")
    print("Error:", e)
    print("Explanation: The shapes of x and v are not compatible for concatenation along axis 0.")

1. Addition of x and y:
[[ 6  8]
 [10 13]]
2. Subtraction of x and y:

[[-4 -4]
 [-4 -3]]
3. Multiplication of x by 3:

[[ 3  6]
 [ 9 15]]
4. Square of each element of x:

[[ 1  4]
 [ 9 25]]
5. Dot products:

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
[[ 9 11]
 [10 12]]

7. Error when concatenating x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The shapes of x and v are not compatible for concatenation along axis 0.


In [125]:
# Problem - 4: Matrix Operations:

In [127]:
# For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ̸= BA.
# 3. Prove (AB)

# T = BTAT

In [129]:
# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A * A^(-1):\n", identity_check)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB != BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(np.dot(A, B))
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_T_A_T)
print("(AB)^T == B^T * A^T:", np.array_equal(AB_T, B_T_A_T))

# Solve the system of linear equations using inverse method
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])
X = np.linalg.solve(A_matrix, B_matrix)
print("Solution X:\n", X)

# Solve using np.linalg.inv
A_inv_matrix = np.linalg.inv(A_matrix)
X_inv = np.dot(A_inv_matrix, B_matrix)
print("Solution X using inverse:\n", X_inv)

A * A^(-1):
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA: True
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T: True
Solution X:
 [ 2.  1. -2.]
Solution X using inverse:
 [ 2.  1. -2.]


In [131]:
# 10.2 Experiment: How Fast is Numpy?

In [1]:
import numpy as np
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]
list2 = [i for i in range(1000001, 2000001)]

# Measure time for element-wise addition
start_time = time.time()
result = [a + b for a, b in zip(list1, list2)]
end_time = time.time()

print("1. Element-wise Addition (Python Lists):")
print("Time taken:", end_time - start_time, "seconds")

array1 = np.arange(1, 1000001)
array2 = np.arange(1000001, 2000001)

start_time = time.time()
result = array1 + array2
end_time = time.time()

print("1. Element-wise Addition (NumPy Arrays):")
print("Time taken:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication
start_time = time.time()
result = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

print("\n2. Element-wise Multiplication (Python Lists):")
print("Time taken:", end_time - start_time, "seconds")

start_time = time.time()
result = array1 * array2
end_time = time.time()

print("2. Element-wise Multiplication (NumPy Arrays):")
print("Time taken:", end_time - start_time, "seconds")

# Measure time for dot product
start_time = time.time()
dot_product = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()

print("\n3. Dot Product (Python Lists):")
print("Time taken:", end_time - start_time, "seconds")

start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()

print("3. Dot Product (NumPy Arrays):")
print("Time taken:", end_time - start_time, "seconds")

# Create two 1000x1000 matrices 
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()

print("\n4. Matrix Multiplication (Python Lists):")
print("Time taken:", end_time - start_time, "seconds")

matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result = np.dot(matrix1_np, matrix2_np)
end_time = time.time()

print("4. Matrix Multiplication (NumPy Arrays):")
print("Time taken:", end_time - start_time, "seconds")

1. Element-wise Addition (Python Lists):
Time taken: 0.1047825813293457 seconds
1. Element-wise Addition (NumPy Arrays):
Time taken: 0.016999483108520508 seconds

2. Element-wise Multiplication (Python Lists):
Time taken: 0.1108083724975586 seconds
2. Element-wise Multiplication (NumPy Arrays):
Time taken: 0.013530492782592773 seconds

3. Dot Product (Python Lists):
Time taken: 0.13235139846801758 seconds
3. Dot Product (NumPy Arrays):
Time taken: 0.0009996891021728516 seconds

4. Matrix Multiplication (Python Lists):
Time taken: 120.32965469360352 seconds
4. Matrix Multiplication (NumPy Arrays):
Time taken: 1.5541505813598633 seconds
